name: fsynth
version: 0.1.0

ghc-options:
  - -Wall -Werror
  - -fshow-warning-groups
  - -Wno-unused-do-bind
  - -Wno-type-defaults
  - -Wwarn=unused-imports
  - -Wwarn=unused-top-binds
  - -Wwarn=type-defaults
  - -rtsopts -threaded -O2

executable:
  source-dirs: src
  main: Main.hs

dependencies:
  # essentially standard library
  - base
  - text
  - containers
  - transformers
  - mtl
  - vector
  # macros
  - template-haskell
  # other
  - dunai
  - sdl2
  
# enable modern Haskell
default-extensions:
  # quality of live
  - PackageImports
  - ImportQualifiedPost
  - LambdaCase
  - OverloadedStrings
  - OverloadedLists
  - TypeApplications
  - TupleSections
  - PatternSynonyms
  - ViewPatterns
  - InstanceSigs
  - RecordWildCards

  # deriving
  - StandaloneDeriving
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - EmptyDataDeriving
  - DerivingVia
  - DeriveGeneric
  - DeriveFunctor
  - DeriveTraversable
  - DeriveFoldable
  - DeriveDataTypeable
  - DeriveLift

  # typesysteme
  - QuantifiedConstraints
  - PolyKinds
  - ExistentialQuantification
  - GADTs
  - DataKinds
  - RankNTypes
  - MultiParamTypeClasses
  - FunctionalDependencies
  - ConstraintKinds
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators
  - ScopedTypeVariables
  - FlexibleInstances
  - FlexibleContexts
  - UndecidableInstances

